Repository jenkinsci/ec2-fleet-plugin, pull requests merged in 2019-07, with the labels that each got.

#109 #76 Don't provision additional capacity until node will be online
  src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncher.java
  src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
  src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineChecker.java
  src/main/java/com/amazon/jenkins/ec2fleet/IdleRetentionStrategy.java
  src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
  src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-initOnlineTimeoutSec.html
  src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineCheckerTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/IntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/RealEc2ApiIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/SingleLocalComputerConnector.java
  src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java
Labels: bug, enhancement

#110 Do connection before wait
  src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineChecker.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineCheckerTest.java
Labels: enhancement

#114 Scale executors by weight
  src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
  src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetNode.java
  src/main/java/com/amazon/jenkins/ec2fleet/FleetStateStats.java
  src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
  src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/help-scaleExecutorsByWeight.html
  src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/FleetStateStatsTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/RealEc2ApiIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java
Labels: enhancement

#32 Scale executors by LaunchSpecification weight
  src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
  src/main/java/com/amazon/jenkins/ec2fleet/FleetStateStats.java
  src/main/java/com/amazon/jenkins/ec2fleet/cloud/FleetNode.java
  src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetCloud/config.jelly
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/RealEc2ApiIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java
Labels: enhancement

#116 Fix empty label for widget
  .gitignore
  src/main/java/com/amazon/jenkins/ec2fleet/CloudNanny.java
  src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
  src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetStatusInfo.java
  src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetStatusWidget.java
  src/main/java/com/amazon/jenkins/ec2fleet/FleetStatusWidget.java
  src/main/resources/com/amazon/jenkins/ec2fleet/EC2FleetStatusWidget/index.jelly
  src/test/java/com/amazon/jenkins/ec2fleet/CloudNannyTest.java
Labels: bug

#127 Reduce amount of describeInstances calls for fleet update
  src/main/java/com/amazon/jenkins/ec2fleet/EC2Api.java
  src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java
  src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2ApiTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/IntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
Labels: enhancement
