Repository jenkinsci/ec2-fleet-plugin, pull requests merged in 2025-08, with the labels that each got.

#479 Prepare release 4.1.0
  README.md
  pom.xml
Labels: skip-changelog

#484 Fleet list was not populating
  pom.xml
  src/main/java/com/amazon/jenkins/ec2fleet/aws/CloudFormationApi.java
  src/main/java/com/amazon/jenkins/ec2fleet/aws/EC2Api.java
  src/main/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleet.java
Labels: bug

#485 Migrate tests to JUnit5
  pom.xml
  src/test/java/com/amazon/jenkins/ec2fleet/AutoResubmitIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/CloudNamesTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/CloudNannyTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetAutoResubmitComputerLauncherTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudConfigurationAsCodeTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetCloudTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloudConfigurationAsCodeTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelCloudIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetLabelParametersTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetNodeComputerTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetOnlineCheckerTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2FleetStatusWidgetUpdaterTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EC2RetentionStrategyTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/EmptyAmazonEC2.java
  src/test/java/com/amazon/jenkins/ec2fleet/IntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategyPerformanceTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategyTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/ProvisionIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/ProvisionPerformanceTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/RealTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/UiIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/aws/AWSUtilsIntegrationTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/aws/EC2ApiTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/aws/RegionInfoTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/fleet/AutoScalingGroupFleetTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/fleet/EC2EC2FleetTest.java
  src/test/java/com/amazon/jenkins/ec2fleet/fleet/EC2SpotFleetTest.java
Labels: tests

#493 Fix for using AWS credential with role
  pom.xml
  src/main/java/com/amazon/jenkins/ec2fleet/aws/AWSUtils.java
Labels: bug
